#!/bin/bash

GIT_ROOT=`dirname ${0}`/../

git diff --stat HEAD~ | grep "\.el" > /dev/null 2>&1
RET_VAL=$?
if [ $RET_VAL -eq 0 ]; then
  echo cleanup elc cache
  ${GIT_ROOT}/cleanup_cache.sh
else
  echo no elisp update
fi
