;;; blackout-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from blackout.el

(autoload 'blackout "blackout" "\
Do not display MODE in the mode line.
If REPLACEMENT is given, then display it instead. REPLACEMENT may
be a string or more generally any mode line construct (see
`mode-line-format').

(fn MODE &optional REPLACEMENT)")
(autoload 'use-package-normalize/:blackout "blackout" "\
Normalize the arguments to `:blackout'.
The return value is an alist whose cars are mode names and whose
cdrs are mode line constructs. For documentation on NAME,
KEYWORD, and ARGS, refer to `use-package'.

(fn NAME KEYWORD ARGS)")
(autoload 'use-package-handler/:blackout "blackout" "\
Handle `:blackout' keyword.
For documentation on NAME, KEYWORD, ARG, REST, and STATE, refer
to `use-package'.

(fn NAME KEYWORD ARG REST STATE)")
(with-eval-after-load 'use-package-core (when (and (boundp 'use-package-keywords) (listp use-package-keywords)) (add-to-list 'use-package-keywords :blackout 'append)))
(register-definition-prefixes "blackout" '("blackout-"))

;;; End of scraped data

(provide 'blackout-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; blackout-autoloads.el ends here
