;;; helm-migemo-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-migemo.el

(autoload 'helm-migemo "helm-migemo" "\
`helm' with migemo extension.
With prefix arugument, `helm-pattern' is migemo-ized, otherwise normal `helm'.

(fn WITH-MIGEMO &rest HELM-ARGS)" t)
(register-definition-prefixes "helm-migemo" '("helm-"))

;;; End of scraped data

(provide 'helm-migemo-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-migemo-autoloads.el ends here
